receitas/urls.py
from django.urls import path

from . import views

app_name = 'receitas'

urlpatterns = [
    path('', views.ReceitaListView.as_view(), name='index'),
    path('search/', views.search_receita, name='search'),
    path('<int:receita_id>/', views.detail_receita, name = 'detail'),
    path('create/', views.create_receita, name='create'),
    path('update/<int:receita_id>/', views.update_receita, name='update'),
    path('delete/<int:receita_id>/', views.delete_receita, name='delete'),
    path('<int:receita_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name = 'category'),
    path('cat_list/<int:category_id>', views.list_category, name = 'cat_list')
]

sitereceita/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('admin/', admin.site.urls),
    path('receitas/', include('receitas.urls')),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

receitas/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class Receita(models.Model):
    name = models.CharField(max_length=250)
    tempo = models.CharField(max_length=250)
    ingredientes = models.TextField()
    modo_prepaor = models.TextField()
    desc = models.CharField(max_length=250)
    image = models.URLField()

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    date = models.DateTimeField(default = timezone.now)
    receita = models.ForeignKey(Receita, on_delete=models.CASCADE)

    def __srt__(self):
        return '{0} - {1}'.format(self.text, self.author.username)

class Category(models.Model):
    name  = models.CharField(max_length = 250)
    description = models.CharField(max_length=250)
    receitas = models.ManyToManyField(Receita)

staticpages/models.py
from django.db import models

# Create your models here.

receitas/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
            'date'
        ]
    labels = {
        'author': "Usuário",
        'text': 'Comentário',
        'date': 'Data',
    }

receitas/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Receita, Comment, Category
from django.shortcuts import render, get_object_or_404
from .forms import CommentForm
from django.views import generic


def detail_receita(request, receita_id):
    receita = get_object_or_404(Receita,pk = receita_id)
    context = {'receitas':receita}
    return render(request, 'receitas/detail.html',context)

def search_receita(request):
    context = {}
    if request.GET.get('query',False):
        search_term = request.GET['query'].lower()
        receita_list = Receita.objects.filter(name__icontains = search_term)
        context = {"receita_list": receita_list}
    return render(request, 'receitas/search.html', context)

def create_receita(request):
    if request.method == 'POST':
        receita_name = request.POST['name']
        receita_dificuldade = request.POST['dificuldade']
        receita_tempo = request.POST['tempo']
        receita_image = request.POST['image']
        receita_desc = request.POST['desc']
        receita_ingredientes = request.POST['ingredientes']
        receita_prepaor = request.POST['modo_prepaor']
        receita_tag1 = request.POST['tag1']
        receita_tag2 = request.POST['tag2']
        receita = Receita(
            name = receita_name,
            dificuldade = receita_dificuldade,
            tempo = receita_tempo,
            image = receita_image,
            desc = receita_desc,
            ingredientes = receita_ingredientes,
            modo_prepaor = receita_prepaor,
            tag1 = receita_tag1,
            tag2 = receita_tag2
        )
        receita.save()
        return HttpResponseRedirect(
            reverse('receitas:detail', args=(receita.id, )))
    else:
        return render(request, 'receitas/create.html', {})

def update_receita(request, receita_id):
    receita = get_object_or_404(Receita, pk = receita_id)

    if request.method == "POST":
        receita.name = request.POST['name']
        receita.dificuldade = request.POST['dificuldade']
        receita.tempo = request.POST['tempo']
        receita.image = request.POST['image']
        receita.desc = request.POST['desc']
        receita.ingredientes = request.POST['ingredientes']
        receita.modo_prepaor = request.POST['modo_prepaor']
        receita.tag1 = request.POST['tag1']
        receita.tag2 = request.POST['tag2']
        receita.save()
        return HttpResponseRedirect(
            reverse('receitas:detail', args=(receita.id, )))

    context = {'receitas':receita}
    return render(request, 'receitas/update.html', context)

def delete_receita(request,receita_id):
    receita = get_object_or_404(Receita, pk = receita_id)

    if request.method == "POST":
        receita.delete()
        return HttpResponseRedirect(reverse('receitas:index'))
    context = {'receitas':receita}
    return render(request, 'receitas/delete.html',context)

def create_comment(request, receita_id):
    receita = get_object_or_404(Receita,pk = receita_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(
                author = comment_author,
                text = comment_text,
                receita = receita
            )
            comment.save()
            return HttpResponseRedirect(
                reverse('receitas:detail', args=(receita_id, ))
            )
    else:
        form = CommentForm()
    context = {'form':form, 'receitas':receita}
    return render(request, 'receitas/comment.html', context)

def list_category(request, category_id):
    tag = get_object_or_404(Category, pk = category_id)
    context = {'category':tag}
    return render(request, 'receitas/cat_list.html', context)

class ReceitaListView(generic.ListView):
    model = Receita
    template_name = 'receitas/index.html'

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'receitas/category.html'

staticpages/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

receitas/templates/receitas/cat_list.html
{% extends 'list.html' %}

{% block content %}
<h2>Receitas: {{category.name}}</h2>
<section>
</section>
{% if category.receitas.all %}
<section class="lista-de-cards">
    {% for receitas in category.receitas.all %}
    
    <article class="card">
        <div class="wrapper">
        <a class = 'card-image' href="{% url 'receitas:detail' receitas.id %}"><img src="{{ receitas.image }}"
                alt="Poster do filme {{ receitas.name}}"></a>
        </div>
        <p class = 'card-name'>{{ receitas.name }}</p>
        <p class = 'card-desc'>{{ receitas.desc }}</p>
    </article>
    <hr>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma receita.</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/category.html
{% extends 'list.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias</h2>

<section>
    {% for tag in category_list %}
    <hr>
    <article>
        <header>
            <a class = 'normal' href = "{% url 'receitas:cat_list' tag.id %}"><h3 class = 'card-name'>{{tag.name}} </h3></a>
            <p class = 'card-desc'>{{tag.description}}</p>
        </header>
        
    </article>
    {% endfor %}
</section>

{% endblock content %}

receitas/templates/receitas/comment.html
{% extends 'list.html' %}

{% block content %}
<h2>Escreva o que achou da receita {{ receitas.name }}</h2>

<form action="{% url 'receitas:comment' receitas.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Adicionar comentário</button>
</form>

<p><a href="{% url 'receitas:detail' receitas.id %}">Voltar para a página do filme</a></p>
{% endblock content %}

receitas/templates/receitas/create.html
{% extends 'list.html' %}

{% block content %}
<h2>Criar uma nova receita</h2>
<form method="POST" action="{% url 'receitas:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Nome da receita</label><br>
        <input type="text" name="name" id="id_name" required=""/>
    </p>
    <p>
        <label for="id_tempo">Tempo de Preparo</label><br>
        <input type="text" name="tempo" id="id_tempo" required=""/>
    </p>
    <p>
        <label for="id_image">URL foto da Comida</label><br>
        <input type="url" name="image" id="id_image" required=""/>
    </p>
    <p>
        <label for="id_desc">Descrição</label><br>
        <input type="text" name="desc" id="id_desc" required=""/>
    </p>
    <p>
        <label for="id_ingredientes">Ingredientes</label><br>
        <textarea name = 'ingredientes' id = 'id_ingredientes' rows = '10' cols ='50' required=""></textarea>
    </p>
    <p>
        <label for="id_modo_prepaor">Modo de Preparo</label><br>
        <textarea name="modo_prepaor" id="id_modo_prepaor" rows="15" cols="50" required=""></textarea>        
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

receitas/templates/receitas/delete.html
{% extends 'list.html' %}

{% block content %}
<form action="{% url 'receitas:delete' receitas.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a receita "{{ receitas.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

receitas/templates/receitas/detail.html
{% extends 'more_det.html' %}

{% block title %}
{{ receitas.name }}
{% endblock title %}

{% block content %}

<li><a class = 'normal' href="{% url 'receitas:update' receitas.id %}">Editar</a></li>
<li><a class = 'normal' href="{% url 'receitas:delete' receitas.id %}">Apagar</a></li>
<section class="dados-de-filme">
    <img src="{{ receitas.image }}" alt="Poster do filme {{ receitas.name}}">
</section>
<hr>
<h2 class = 'titulo'>{{ receitas.name }}</h2>
<p>Tags:{% if receitas.category_set.all %}
            {% for tags in receitas.category_set.all %}
                <a class = 'normal', href = "{% url 'receitas:cat_list' tags.id %}"><b> {{tags.name}},</b></a>
            {% endfor %}
        {% endif %} </p>
        
<p class = 'dificuldade'>Tempo de Preparo: {{receitas.tempo}}</p>
<h3 class = 'titulo'>Ingredientes</h3>
<p class = 'normal-text'>{{receitas.ingredientes|linebreaks}}</p>
<h3 class = 'titulo'>Modo de preparo</h3>
<p class = 'normal-text'>{{receitas.modo_prepaor|linebreaks}}</p>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if receitas.comment_set.all %}
            {% for comentario in receitas.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comentario.text }}"
                    </blockquote>
                    <figcaption>—{{ comentario.author }}: {{comentario.date}}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não temos nenhum comentário sobre a receita.</p>
        {% endif %}
    </ul>
    <hr>

    <a href="{% url 'receitas:comment' receitas.pk %}"><button>Adicione um Comentário</button></a>
</section>
</section>
{% endblock content %}

receitas/templates/receitas/index.html
{% extends 'list.html' %}

{% block content %}
<h2>Receitas</h2>
<section>
    <p>Muitos resultados? <a class = 'botao' href="{% url 'receitas:search' %}"><br>Buscar Receita</a></p>
    <p><a class = 'botao' href="{% url 'receitas:create' %}">Criar nova Receita</a></p>
</section>
{% if receita_list %}
<section class="lista-de-cards">
    {% for receitas in receita_list %}
    
    <article class="card">
        <div class="wrapper">
        <a class = 'card-image' href="{% url 'receitas:detail' receitas.id %}"><img src="{{ receitas.image }}"
                alt="Poster do filme {{ receitas.name}}"></a>
        </div>
        <p class = 'card-name'>{{ receitas.name }}</p>
        <p class = 'card-desc'>{{ receitas.desc }}</p>
    </article>
    <hr>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma receita.</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/search.html
{% extends 'list.html' %}

{% block content %}
<h2>Busca de Receitas por Nome</h2>
<form action="{% url 'receitas:search' %}">
    <p>
        <label for="id_query">Nome da Receita</label><br>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>
<hr>

<h2>Resultado da Busca</h2>
{% if receita_list %}
<section class="lista-de-cards">
    {% for receitas in receita_list %}
    <article class="card">
        <div class="wrapper">
        <a class = 'card-image' href="{% url 'receitas:detail' forloop.counter %}"><img src="{{ receitas.image }}"
                alt="Poster do filme {{ receitas.name}}"></a>
        </div>
        <p class = 'card-name'>{{ receitas.name }}</p>
        <p class = 'card-desc'>{{ receitas.desc }}</p>
        <hr>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma receita ainda.</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/update.html
{% extends 'list.html' %}

{% block content %}
<h2>Atualizar a Receita</h2>
<form method="POST" action="{% url 'receitas:update' receitas.id%}">
    {% csrf_token %}
    <p>
        <label for="id_name">Nome da receita</label><br>
        <input type="text" name="name" id="id_name" value = "{{receitas.name}}" />
    </p>
    <p>
        <label for="id_tempo">Tempo de Preparo</label><br>
        <input type="text" name="tempo" id="id_tempo" value = "{{receitas.tempo}}"/>
    </p>
    <p>
        <label for="id_image">URL foto da Comida</label><br>
        <input type="url" name="image" id="id_image" value = "{{receitas.image}}" />
    </p>
    <p>
        <label for="id_desc">Descrição</label><br>
        <input type="text" name="desc" id="id_desc" value = "{{receitas.desc}}"/>
    </p>
    <p>
        <label for="id_ingredientes">Ingredientes</label><br>
        <textarea name = 'ingredientes' id = 'id_ingredientes' rows = '10' cols ='50'>{{receitas.ingredientes}}</textarea>
    </p>
    <p>
        <label for="id_modo_prepaor">Modo de Preparo</label><br>
        <textarea name="modo_prepaor" id="id_modo_prepaor" rows="15" cols="50">{{receitas.modo_prepaor}}</textarea>        
    </p>
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>WikiReceitas</i></h1>
<p>A enciclopédia de receitas</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Site de Receita
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>WikiReceitas</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href = "{% url 'receitas:index' %}">Receitas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'receitas:category' %}">Tags</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>
</html>

templates/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Site de Receita
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Allerta' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Bubbler One' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'style_list.css' %}">
</head>
<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>WikiReceitas</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href = "{% url 'receitas:index' %}">Receitas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'receitas:category' %}">Tags</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>
</html>

templates/more_det.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Site de Receita
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Allerta' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Bubbler One' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'style_det.css' %}">
</head>
<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}">
            <p>WikiReceitas</p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href = "{% url 'receitas:index' %}">Receitas</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'receitas:category' %}">Tags</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>
</html>